name: umetaflow-pyopenms
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.10
  - pip==24.0
  - mono==6.12.0.90
  - sirius-ms==5.8.6
  - bioconda::thermorawfileparser
  - pip: # dependencies only available through pip
    - pyopenms==3.1
    - numpy==1.26.4 # pyopenms needs numpy<=1.26.4
    - pyopenms_viz>=0.1.2 # for visualization, not strictly necessary
    - pyteomics
    - plotly
    - jupyter
    - wget